const CREATE = "CREATE";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const LIKE = "LIKE";
const FETCH_ALL = "FETCH_ALL";

const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";

const AUTH = "AUTH";

const LOGOUT = "LOGOUT";

const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";

const FETCH_POST = "FETCH_POST";

const COMMENT = "COMMENT";
const UPDATE_ACTIVE_USER = "UPDATE_ACTIVE_USER";
const DELETE_USER = "DELETE_USER";
const FETCH_ALL_PRODUCT = "FETCH_ALL_PRODUCT";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const FETCH_ALL_CATEGORY = "FETCH_ALL_CATEGORY";
const FETCH_USER_PRODUCTS = "FETCH_USER_PRODUCTS";
const FETCH_ONE_PRODUCT = "FETCH_ONE_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const SET_SPECIFIC_USER = "SET_SPECIFIC_USER";
const END_CATEGORY_LOADING = "END_CATEGORY_LOADING";
const START_CATEGORY_LOADING = "START_CATEGORY_LOADING";
const GET_CATEGORY_W_PRODUCTS = "GET_CATEGORY_W_PRODUCTS";
const FETCH_LOGGED_USER_PRODUCTS = "FETCH_LOGGED_USER_PRODUCTS";
const CREATE_OFFER = "CREATE_OFFER";
const START_OFFER_LOADING = "START_OFFER_LOADING";
const END_OFFER_LOADING = "END_OFFER_LOADING";
const FETCH_LOGGED_USER_INCOMING_OFFERS = "FETCH_LOGGED_USER_INCOMING_OFFERS";
const FETCH_SPECIFIC_USER_INCOMING_OFFERS = "FETCH_SPECIFIC_USER_INCOMING_OFFERS";


export {
  CREATE,
  UPDATE,
  DELETE,
  LIKE,
  FETCH_ALL,
  AUTH,
  LOGOUT,
  FETCH_BY_SEARCH,
  START_LOADING,
  END_LOADING,
  FETCH_POST,
  COMMENT,
  UPDATE_ACTIVE_USER,
  DELETE_USER,
  FETCH_ALL_PRODUCT,
  FETCH_ALL_CATEGORY,
  CREATE_PRODUCT,
  FETCH_USER_PRODUCTS,
  FETCH_ONE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  SET_SPECIFIC_USER,
  END_CATEGORY_LOADING,
    START_CATEGORY_LOADING,
  GET_CATEGORY_W_PRODUCTS,
  FETCH_LOGGED_USER_PRODUCTS,
  CREATE_OFFER,
  START_OFFER_LOADING,
    END_OFFER_LOADING,
  FETCH_LOGGED_USER_INCOMING_OFFERS,
  FETCH_SPECIFIC_USER_INCOMING_OFFERS
};
